# http://docs.travis-ci.com/user/languages/go/
language: go

go: 1.10

services:
  - docker

os:
  - linux

env:
- MYSQL_USER=root

before_install:
  - docker build -t orchestrator-travis-build .
  - mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

install: true

script: script/cibuild

notifications:
  email: false
