name: system tests

on: [pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     backend: [sqlite, MySQL]

    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12

    - name: Start local MySQL
      run: sudo /etc/init.d/mysql start

    - name: check out
      uses: actions/checkout@v2

    - name: build
      run:  script/test-build

    - name: deploy as service
      run: |
        sudo cp etc/systemd/orchestrator.service /etc/systemd/system/orchestrator.service
        sudo mkdir -p /usr/local/orchestrator
        sudo cp bin/orchestrator /usr/local/orchestrator/
        sudo cp conf/orchestrator-ci-system.conf.json /etc/orchestrator.conf.json
        sudo systemctl daemon-reload

    - name: run orchestrator service
      run: |
        sudo systemctl start orchestrator

    - name: check orchestrator service
      run: |
        sudo systemctl status orchestrator
